### ISSUE TITLE
Does it support Linux

### ISSUE THREAD

**Issue by gaocegege** [vegasbrianc/K8s-demo#1]
Hi, I am a member from [kubeflow](https://github.com/kubeflow/kubeflow), and we are investigating [running our CRD controller and other components on Kubernetes via docker](https://github.com/kubeflow/kubeflow/issues/218). Then I have one question: does it support Linux?

I'd appreciate if you could help.

**Comment by vegasbrianc** [comment]
@gaocegege Does the demo support Linux or Kubernertes on Docker? My understanding Linux is on the edge release but will be available very soon. I can say it works well on Mac

**Comment by gaocegege** [comment]
@vegasbrianc Thanks for your reply 😄 

I am closing the issue.
